import { z } from "zod";

const CatModel = z.object({
  /**
   * The unique identifier for the Cat
   * @default {Generated by database}
   */
  id: z.string().cuid(),
  /**
   * The name of the Cat
   */
  name: z
    .string()
    .min(1)
    .max(50, { message: "Must be less than 50 characters long" }),
  nick_name: z.string().nullish(),
  is_fluffy: z.boolean(),
});

export { CatModel };
